version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 2
    commit-message:
      prefix: chore
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
      npm-major:
        update-types:
          - major
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    groups:
      github-actions:
        patterns:
          - "*"
